<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Staff Birthdays List - PDF</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            color: #333;
        }
        h1 {
            color: #003471;
            text-align: center;
            border-bottom: 3px solid #003471;
            padding-bottom: 10px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th {
            background-color: #003471;
            color: white;
            padding: 12px;
            text-align: left;
            font-weight: bold;
        }
        td {
            padding: 10px;
            border-bottom: 1px solid #ddd;
        }
        tr:nth-child(even) {
            background-color: #f8f9fa;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            color: #666;
            font-size: 12px;
        }
        @media print {
            body {
                margin: 0;
            }
        }
    </style>
</head>
<body>
    <h1>Staff Birthdays List</h1>
    <p><strong>Generated:</strong> {{ date('Y-m-d H:i:s') }}</p>
    
    <table>
        <thead>
            <tr>
                <th>EMP Code</th>
                <th>Name</th>
                <th>Father/Husband</th>
                <th>Birthday</th>
                <th>Status</th>
                <th>Wish</th>
            </tr>
        </thead>
        <tbody>
            @forelse($staff as $member)
                <tr>
                    <td>{{ $member['emp_code'] }}</td>
                    <td>{{ $member['name'] }}</td>
                    <td>{{ $member['father_husband'] }}</td>
                    <td>{{ \Carbon\Carbon::parse($member['birthday'])->format('d M Y') }}</td>
                    <td>{{ $member['status'] }}</td>
                    <td>{{ $member['wish'] }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="6" style="text-align: center; padding: 20px;">No staff birthdays found.</td>
                </tr>
            @endforelse
        </tbody>
    </table>
    
    <div class="footer">
        <p>Total Records: {{ count($staff) }}</p>
        <p>Generated by School Management System</p>
    </div>
</body>
</html>

