<!DOCTYPE html>
<html>
<head>
    <title>Job Inquiries List</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            margin: 20px;
        }
        h1 {
            color: #003471;
            text-align: center;
            margin-bottom: 20px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #003471;
            color: white;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f2f2f2;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #666;
        }
    </style>
</head>
<body>
    <h1>Job Inquiries List</h1>
    <p><strong>Generated:</strong> {{ date('Y-m-d H:i:s') }}</p>
    
    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>Father/Husband</th>
                <th>Campus</th>
                <th>Gender</th>
                <th>Phone</th>
                <th>Qualification</th>
                <th>Applied For</th>
                <th>Email</th>
            </tr>
        </thead>
        <tbody>
            @forelse($inquiries as $inquiry)
                <tr>
                    <td>{{ $loop->iteration }}</td>
                    <td>{{ $inquiry->name }}</td>
                    <td>{{ $inquiry->father_husband_name ?? 'N/A' }}</td>
                    <td>{{ $inquiry->campus ?? 'N/A' }}</td>
                    <td>{{ $inquiry->gender ?? 'N/A' }}</td>
                    <td>{{ $inquiry->phone ?? 'N/A' }}</td>
                    <td>{{ $inquiry->qualification ?? 'N/A' }}</td>
                    <td>{{ $inquiry->applied_for_designation ?? 'N/A' }}</td>
                    <td>{{ $inquiry->email ?? 'N/A' }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="9" style="text-align: center; padding: 20px;">No job inquiries found.</td>
                </tr>
            @endforelse
        </tbody>
    </table>
    
    <div class="footer">
        <p>Total Records: {{ count($inquiries) }}</p>
        <p>Generated by School Management System</p>
    </div>
</body>
</html>

