<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Account Requests List - PDF</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            color: #333;
        }
        h1 {
            color: #003471;
            text-align: center;
            border-bottom: 3px solid #003471;
            padding-bottom: 10px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th {
            background-color: #003471;
            color: white;
            padding: 12px;
            text-align: left;
            font-weight: bold;
        }
        td {
            padding: 10px;
            border-bottom: 1px solid #ddd;
        }
        tr:nth-child(even) {
            background-color: #f8f9fa;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            color: #666;
            font-size: 12px;
        }
        @media print {
            body {
                margin: 0;
            }
        }
    </style>
</head>
<body>
    <h1>Account Requests List</h1>
    <p><strong>Generated:</strong> {{ date('Y-m-d H:i:s') }}</p>
    
    <table>
        <thead>
            <tr>
                <th>Parent ID</th>
                <th>Request By</th>
                <th>Email</th>
                <th>Phone</th>
                <th>ID Card</th>
                <th>Request Status</th>
                <th>Created At</th>
            </tr>
        </thead>
        <tbody>
            @forelse($requests as $request)
                <tr>
                    <td>{{ $request->parent_id ?? 'N/A' }}</td>
                    <td>{{ $request->request_by ?? 'N/A' }}</td>
                    <td>{{ $request->email ?? 'N/A' }}</td>
                    <td>{{ $request->phone ?? 'N/A' }}</td>
                    <td>{{ $request->id_card ?? 'N/A' }}</td>
                    <td>{{ $request->request_status ?? 'Pending' }}</td>
                    <td>{{ $request->created_at->format('Y-m-d H:i:s') }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="7" style="text-align: center; padding: 20px;">No account requests found.</td>
                </tr>
            @endforelse
        </tbody>
    </table>
    
    <div class="footer">
        <p>Total Records: {{ count($requests) }}</p>
        <p>Generated by School Management System</p>
    </div>
</body>
</html>

