<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Parent Accounts List - PDF</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            color: #333;
        }
        h1 {
            color: #003471;
            text-align: center;
            border-bottom: 3px solid #003471;
            padding-bottom: 10px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th {
            background-color: #003471;
            color: white;
            padding: 12px;
            text-align: left;
            font-weight: bold;
        }
        td {
            padding: 10px;
            border-bottom: 1px solid #ddd;
        }
        tr:nth-child(even) {
            background-color: #f8f9fa;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            color: #666;
            font-size: 12px;
        }
        @media print {
            body {
                margin: 0;
            }
        }
    </style>
</head>
<body>
    <h1>Parent Accounts List</h1>
    <p><strong>Generated:</strong> {{ date('Y-m-d H:i:s') }}</p>
    
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Email</th>
                <th>Phone</th>
                <th>WhatsApp</th>
                <th>ID Card Number</th>
                <th>Address</th>
                <th>Profession</th>
                <th>Created At</th>
            </tr>
        </thead>
        <tbody>
            @forelse($parents as $parent)
                <tr>
                    <td>{{ $parent->id }}</td>
                    <td>{{ $parent->name }}</td>
                    <td>{{ $parent->email }}</td>
                    <td>{{ $parent->phone ?? 'N/A' }}</td>
                    <td>{{ $parent->whatsapp ?? 'N/A' }}</td>
                    <td>{{ $parent->id_card_number ?? 'N/A' }}</td>
                    <td>{{ Str::limit($parent->address ?? 'N/A', 50) }}</td>
                    <td>{{ $parent->profession ?? 'N/A' }}</td>
                    <td>{{ $parent->created_at->format('Y-m-d H:i:s') }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="9" style="text-align: center; padding: 20px;">No parent accounts found.</td>
                </tr>
            @endforelse
        </tbody>
    </table>
    
    <div class="footer">
        <p>Total Records: {{ count($parents) }}</p>
        <p>Generated by School Management System</p>
    </div>
</body>
</html>

