<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Student Birthdays List - PDF</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            color: #333;
        }
        h1 {
            color: #003471;
            text-align: center;
            border-bottom: 3px solid #003471;
            padding-bottom: 10px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th {
            background-color: #003471;
            color: white;
            padding: 12px;
            text-align: left;
            font-weight: bold;
        }
        td {
            padding: 10px;
            border-bottom: 1px solid #ddd;
        }
        tr:nth-child(even) {
            background-color: #f8f9fa;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            color: #666;
            font-size: 12px;
        }
        @media print {
            body {
                margin: 0;
            }
        }
    </style>
</head>
<body>
    <h1>Student Birthdays List</h1>
    <p><strong>Generated:</strong> {{ date('Y-m-d H:i:s') }}</p>
    
    <table>
        <thead>
            <tr>
                <th>Roll</th>
                <th>Student</th>
                <th>Parent</th>
                <th>Class</th>
                <th>Section</th>
                <th>Birthday</th>
                <th>Status</th>
                <th>Birthday Card</th>
                <th>Wish</th>
            </tr>
        </thead>
        <tbody>
            @forelse($students as $student)
                <tr>
                    <td>{{ $student['roll'] }}</td>
                    <td>{{ $student['student'] }}</td>
                    <td>{{ $student['parent'] }}</td>
                    <td>{{ $student['class'] }}</td>
                    <td>{{ $student['section'] }}</td>
                    <td>{{ \Carbon\Carbon::parse($student['birthday'])->format('d M Y') }}</td>
                    <td>{{ $student['status'] }}</td>
                    <td>{{ $student['birthday_card'] }}</td>
                    <td>{{ $student['wish'] }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="9" style="text-align: center; padding: 20px;">No student birthdays found.</td>
                </tr>
            @endforelse
        </tbody>
    </table>
    
    <div class="footer">
        <p>Total Records: {{ count($students) }}</p>
        <p>Generated by School Management System</p>
    </div>
</body>
</html>

